chain_client:
  archive:
    dest: root:123456:localhost:3306
    secret_key: xxx
    type: mysql
  chain_id: chain1
  nodes:
  - conn_cnt: 10
    enable_tls: true
    node_addr: 10.112.113.215:12301
    tls_host_name: chainmaker.org
    trust_root_paths:
    - ./build/config/node1/ca
  org_id: wx-org1.chainmaker.org
  rpc_client:
    max_receive_message_size: 16
  user_crt_file_path: ./build/config/node1/user/client1/client1.tls.crt
  user_key_file_path: ./build/config/node1/user/client1/client1.tls.key
  user_sign_crt_file_path: ./build/config/node1/user/client1/client1.sign.crt
  user_sign_key_file_path: ./build/config/node1/user/client1/client1.sign.key
